/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portafolio;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author Felipe
 */
public class categoria extends javax.swing.JFrame {
conexion con = Portafolio.conexion;
    /**
     * Creates new form categoria
     */
    public categoria() {
        initComponents();
        this.setTitle("Categoria");
        
        this.setResizable(false);
        //Línea 1
        this.setSize(new Dimension(500, 500));
        
        //Línea 2
        this.setMinimumSize(new Dimension(500, 250));
        this.setLocationRelativeTo(categoria.this);
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagen/descarga.jpg"));
        this.setIconImage(ico);
        
         jButton4.setEnabled(false);
        jButton2.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombrecategoria = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombrecat = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        nombrecategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrecategoriaActionPerformed(evt);
            }
        });
        nombrecategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombrecategoriaKeyTyped(evt);
            }
        });
        getContentPane().add(nombrecategoria);
        nombrecategoria.setBounds(190, 140, 120, 20);

        jButton1.setText("Ingresar categoria");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 270, 160, 23);

        jButton3.setText("verificar ");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 140, 150, 20);

        jButton2.setText("modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 270, 110, 23);

        jButton4.setText("eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(380, 270, 90, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Categoria:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 140, 150, 22);

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(220, 350, 110, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Color-fondo-blog.jpg"))); // NOI18N
        jLabel1.setText("mn");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 530);
        getContentPane().add(nombrecat);
        nombrecat.setBounds(200, 170, 100, 30);

        jMenu2.setText("Volver");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu1.setText("Cerrar sesión");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        principal principal = new principal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    
    private void nombrecategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrecategoriaActionPerformed
       
    }//GEN-LAST:event_nombrecategoriaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       
        String ca;
        
         if (nombrecategoria.getText().equals("") || nombrecategoria.getText().equals(null) ){
            JOptionPane.showMessageDialog(rootPane,"No deje campos en blanco");
        } else {
        try{
        
         ca=nombrecategoria.getText();
                      

         String sql = "INSERT INTO categoria (descripcion)VALUES('"+ca+"')";
        
        PreparedStatement ps=con.getConexion().prepareStatement(sql);
            
            //ps.setBinaryStream(4,fis,longitudBytes);
            
            ps.execute();
            ps.close();
            
            nombrecategoria.setText("");
        
         JOptionPane.showMessageDialog(null, "Datos CATEGORIA Almacenados Satisfactoriamente"); 
          //  ps.execute();
           
            //ps.close();
          JOptionPane.showMessageDialog(rootPane,"Guardado correctamente");
        }catch(SQLException | NumberFormatException | HeadlessException x){
            JOptionPane.showMessageDialog(rootPane, "exception 2 "+x);
        }  
         }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        inicio inicio = new inicio();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
      String nombre=nombrecategoria.getText();    
    String sql="select * from categoria where descripcion='"+nombre+"'";      
        String r;
        String a;
        String b;     
        
        if(nombrecategoria.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Para buscar debe ingresar el nombre de categoria");
        }
        else{
            
        
        try{
            
            ResultSet rs = con.ejecutarSQLSelect(sql);
            if (rs.next()){
                
                 
                 r = rs.getString("descripcion");
                 JOptionPane.showMessageDialog(rootPane,"El nombre es valido");
                
                
               nombrecat.setText(r);
              
               jButton4.setEnabled(true);
               jButton2.setEnabled(true);
               jButton1.setEnabled(false);
               
            }else{
                JOptionPane.showMessageDialog(rootPane,"No existe el nombre de esa categoria");
            }
            
            
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"No existe Categoria ingresada");
            
        }
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if (nombrecategoria.getText().equals("") || nombrecategoria.getText().equals(null) ){
            JOptionPane.showMessageDialog(rootPane,"No deje campos en blanco");
        } else {
       
        try{
        

         String sql = "delete from categoria where descripcion='"+nombrecat.getText()+"'";
        
        PreparedStatement ps=con.getConexion().prepareStatement(sql);
            
            //ps.setBinaryStream(4,fis,longitudBytes);
            
            ps.execute();
            ps.close();
        
         JOptionPane.showMessageDialog(null, "Datos Eliminados Satisfactoriamente"); 
         jButton4.setEnabled(false);
         jButton2.setEnabled(false);
         jButton1.setEnabled(true);
        
            //ps.execute();
           
            //ps.close();
          
        }catch(SQLException | NumberFormatException | HeadlessException x){
            JOptionPane.showMessageDialog(rootPane, "exception 2 "+x);
        }    
        nombrecategoria.setText(null);
        nombrecat.setText(null);
       
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String nam = nombrecategoria.getText();
      
       
        if (nombrecategoria.getText().equals("") ){
            JOptionPane.showMessageDialog(rootPane,"No deje campos en blanco");
        } else {
             
       
        try{
        

         String sql = "update categoria set descripcion='"+nam+"' where descripcion='"+nombrecat.getText()+"'";
        
        PreparedStatement ps=con.getConexion().prepareStatement(sql);

            //ps.setBinaryStream(4,fis,longitudBytes);
            
            ps.execute();
            ps.close();
            nombrecat.setText("");
            
            jButton4.setEnabled(false);
            jButton2.setEnabled(false);
            jButton1.setEnabled(true);
        
        
          JOptionPane.showMessageDialog(rootPane,"Guardado correctamente");
        }catch(SQLException | NumberFormatException | HeadlessException x){
            JOptionPane.showMessageDialog(rootPane, "exception 2 "+x);
        }    
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nombrecategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombrecategoriaKeyTyped
    int n=20;
        if(nombrecategoria.getText().length()>n){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"solo 20 dijitos");
       
        }
         char c=evt.getKeyChar();
        if(((c<'a' || c>'z')&&(c<'A')|c>'Z') &&(c!='ñ')&& ( c!='Ñ')  && c!= KeyEvent.VK_SPACE)evt.consume(); 
    }//GEN-LAST:event_nombrecategoriaKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        nombrecategoria.setText(null);
        jButton1.setEnabled(true);
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new categoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel nombrecat;
    private javax.swing.JTextField nombrecategoria;
    // End of variables declaration//GEN-END:variables
}
