/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portafolio;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static portafolio.usuario.validarRut;

/**
 *
 * @author Roy
 */
public class crear_usuario extends javax.swing.JFrame {
    conexion con = Portafolio.conexion;


    /**
     * Creates new form crear_usuario
     */
    public crear_usuario() {
        initComponents();
        
        this.setTitle("Crear Usuario");
        
        this.setResizable(false);
        //Línea 1
        this.setSize(new Dimension(500, 500));
        
        //Línea 2
        this.setMinimumSize(new Dimension(700, 250));
        this.setLocationRelativeTo(crear_usuario.this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        rut_funcionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombre_usuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        clave1 = new javax.swing.JPasswordField();
        clave2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 310, 80, 23);

        rut_funcionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rut_funcionarioKeyTyped(evt);
            }
        });
        getContentPane().add(rut_funcionario);
        rut_funcionario.setBounds(260, 150, 120, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Usuario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 100, 140, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confimar Clave:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 240, 130, 14);

        nombre_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_usuarioActionPerformed(evt);
            }
        });
        nombre_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_usuarioKeyTyped(evt);
            }
        });
        getContentPane().add(nombre_usuario);
        nombre_usuario.setBounds(260, 100, 120, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rut Funcionario:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 150, 140, 14);

        clave1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clave1KeyTyped(evt);
            }
        });
        getContentPane().add(clave1);
        clave1.setBounds(260, 190, 120, 20);

        clave2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clave2KeyTyped(evt);
            }
        });
        getContentPane().add(clave2);
        clave2.setBounds(260, 240, 120, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Clave:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 200, 60, 14);

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 310, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Color-fondo-blog.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -10, 770, 530);

        jMenu1.setText("Volver");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cerrar sesion");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          String rut=rut_funcionario.getText();
        String nom_usuario=nombre_usuario.getText();
        
       
        String pass1 = String.valueOf(clave1.getPassword());
        String pass2 = String.valueOf(clave2.getPassword());

        //System.out.print(pass1);
        //contra1.setText(valorPass1);
        //System.out.print(pass2);
        //contra2.setText(valorPass2);
        
       
        if(rut.contains("0")){
            rut = rut.substring(0,rut.length()-1);
            rut = rut + "k";
           
        }
        boolean respuesta;
        respuesta = validarRut(rut);
       
        if(respuesta==false ){
            JOptionPane.showMessageDialog(rootPane,"Rut invalido",
            "ERROR", JOptionPane.ERROR_MESSAGE);

        }else{
       
        
        
        try{
        
        
                      

         String sql = "INSERT INTO usuario (funcionario_rut,nombre,clave)VALUES("+rut+",'"+nom_usuario+"','"+clave1.getPassword()+"')";
        
       
        PreparedStatement ps=con.getConexion().prepareStatement(sql);
          // ps.setBinaryStream(4,fis,longitudBytes);
            //ps.setBinaryStream(4,fis,longitudBytes);
            if(pass1.equals(pass2)){
                 JOptionPane.showMessageDialog(null, "Datos Almacenados Satisfactoriamente"); 
            ps.execute();
            ps.close();
            }else{
                 JOptionPane.showMessageDialog(rootPane,"Error Confirmar Contraseña",
            "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        
            //ps.execute();
            //ps.close();
        
          
        }catch(SQLException | NumberFormatException | HeadlessException x){
            JOptionPane.showMessageDialog(rootPane, "exception 2 "+x);
        }
        
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

      public static boolean validarRut(String rut) {

boolean validacion = false;
try {
rut =  rut.toUpperCase();
rut = rut.replace(".", "");
rut = rut.replace("-", "");
int rutAux = Integer.parseInt(rut.substring(0, rut.length() - 1));

char dv = rut.charAt(rut.length() - 1);

int m = 0, s = 1;
for (; rutAux != 0; rutAux /= 10) {
s = (s + rutAux % 10 * (9 - m++ % 6)) % 11;
}
if (dv == (char) (s != 0 ? s + 47 : 75)) {
validacion = true;
}

} catch (java.lang.NumberFormatException e) {
} catch (Exception e) {
}
return validacion;
}
    private void nombre_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_usuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       nombre_usuario.setText("");
       rut_funcionario.setText("");
       clave1.setText("");
       clave2.setText("");


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
          menu_usuario menu_usuario = new menu_usuario();
        menu_usuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void rut_funcionarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rut_funcionarioKeyTyped
        if(rut_funcionario.getText().length()>9){
           evt.consume();
           getToolkit().beep();
           JOptionPane.showMessageDialog(rootPane,"solo 9 digitos");
       
        }
        char c=evt.getKeyChar();
               if(c<'0' || c>'9'){
                   evt.consume();
               }  
    }//GEN-LAST:event_rut_funcionarioKeyTyped

    private void nombre_usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_usuarioKeyTyped
       if(nombre_usuario.getText().length()>15){
           evt.consume();
           getToolkit().beep();
           JOptionPane.showMessageDialog(rootPane,"solo 15 digitos");
       
        }
    }//GEN-LAST:event_nombre_usuarioKeyTyped

    private void clave1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clave1KeyTyped
       if( String.valueOf(clave1.getPassword()).length()>15){
           evt.consume();
           getToolkit().beep();
           JOptionPane.showMessageDialog(rootPane,"solo 15 digitos");
       
        }
    }//GEN-LAST:event_clave1KeyTyped

    private void clave2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clave2KeyTyped
        if( String.valueOf(clave2.getPassword()).length()>15){
           evt.consume();
           getToolkit().beep();
           JOptionPane.showMessageDialog(rootPane,"solo 15 digitos");
       
        }
    }//GEN-LAST:event_clave2KeyTyped

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
     inicio inicio = new inicio();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crear_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crear_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crear_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crear_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crear_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField clave1;
    private javax.swing.JPasswordField clave2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField nombre_usuario;
    private javax.swing.JTextField rut_funcionario;
    // End of variables declaration//GEN-END:variables
}
