/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portafolio;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Roy
 */
public class estado extends javax.swing.JFrame {
    conexion con = Portafolio.conexion;

    /**
     * Creates new form estado
     */
    public estado() {
        initComponents();
        this.setResizable(false);
        
         this.setSize(new Dimension(500, 500));
        
        //Línea 2
        this.setMinimumSize(new Dimension(700, 250));
        this.setLocationRelativeTo(estado.this);
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagen/descarga.jpg"));
        this.setIconImage(ico);
           jButton2.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        nom_estado = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        getContentPane().setLayout(null);

        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });
        estado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                estadoKeyTyped(evt);
            }
        });
        getContentPane().add(estado);
        estado.setBounds(210, 60, 127, 20);

        jButton1.setText("ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 170, 110, 23);

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 170, 130, 23);

        jButton4.setText("Verificar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(390, 60, 90, 23);

        nom_estado.setEnabled(false);
        getContentPane().add(nom_estado);
        nom_estado.setBounds(112, 61, 0, 0);

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(430, 170, 120, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Color-fondo-blog.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -80, 1080, 590);

        jMenu1.setText("Volver");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String nam = estado.getText();
      
       
        if (estado.getText().equals("") ){
            JOptionPane.showMessageDialog(rootPane,"No deje campos en blanco");
        } else {
             
       
        try{
        

         String sql = "update estado set descripcion='"+nam+"' where descripcion='"+nom_estado.getText()+"'";
        
        PreparedStatement ps=con.getConexion().prepareStatement(sql);

            //ps.setBinaryStream(4,fis,longitudBytes);
            
            ps.execute();
            ps.close();
            estado.setText("");
            nom_estado.setText("");
            
           
            jButton2.setEnabled(false);
            jButton1.setEnabled(true);
        
        
          JOptionPane.showMessageDialog(rootPane,"Guardado correctamente");
        }catch(SQLException | NumberFormatException | HeadlessException x){
            JOptionPane.showMessageDialog(rootPane, "exception 2 "+x);
        }    
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
     String ca;
        
         if (estado.getText().equals("") || estado.getText().equals(null) ){
            JOptionPane.showMessageDialog(rootPane,"No deje campos en blanco");
        } else {
        try{
        
         ca=estado.getText();
                      

         String sql = "INSERT INTO estado (descripcion)VALUES('"+ca+"')";
        
        PreparedStatement ps=con.getConexion().prepareStatement(sql);
            
            //ps.setBinaryStream(4,fis,longitudBytes);
            
            ps.execute();
            ps.close();
            
            estado.setText("");
        
         JOptionPane.showMessageDialog(null, "Datos ESTADO Almacenados Satisfactoriamente"); 
          //  ps.execute();
           
            //ps.close();
          JOptionPane.showMessageDialog(rootPane,"Guardado correctamente");
        }catch(SQLException | NumberFormatException | HeadlessException x){
            JOptionPane.showMessageDialog(rootPane, "exception 2 "+x);
        }  
         }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
         principal principal = new principal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1ActionPerformed

    
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
      String nombre=estado.getText();    
    String sql="select * from estado where descripcion='"+nombre+"'";      
        String r;
        String a;
        String b;     
        
        if(estado.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Para buscar debe ingresar el nombre de categoria");
        }
        else{
            
        
        try{
            
            ResultSet rs = con.ejecutarSQLSelect(sql);
            if (rs.next()){
                
                 
                 r = rs.getString("descripcion");
                 JOptionPane.showMessageDialog(rootPane,"El nombre es valido");
                
                
               nom_estado.setText(r);
              
              
               jButton2.setEnabled(true);
               jButton1.setEnabled(false);
               
            }else{
                JOptionPane.showMessageDialog(rootPane,"No existe ");
            }
            
            
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"No existe Estado ingresada");
            
        }
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseEntered

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        principal principal = new principal();
        principal.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void estadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estadoKeyTyped
       if(estado.getText().length()>50){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"solo 50 caracteres");
       
        }
         char c=evt.getKeyChar();
        if(((c<'a' || c>'z')&&(c<'A')|c>'Z')  &&(c!='ñ')&&( c!='Ñ')  && (c!= KeyEvent.VK_SPACE))evt.consume();
    }//GEN-LAST:event_estadoKeyTyped

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        estado.setText(null);
        jButton1.setEnabled(true);
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(estado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new estado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel nom_estado;
    // End of variables declaration//GEN-END:variables
}
