/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portafolio;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class funcionarios extends javax.swing.JFrame {

    conexion con = Portafolio.conexion;
    public funcionarios() {
        initComponents();
         this.setTitle("Funcionarios");
        
        this.setResizable(false);
        //Línea 1
        this.setSize(new Dimension(500, 500));
        
        //Línea 2
        this.setMinimumSize(new Dimension(700, 250));
        this.setLocationRelativeTo(funcionarios.this);
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagen/descarga.jpg"));
        this.setIconImage(ico);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        rut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        mat = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rut:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 50, 33, 22);

        rut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rutKeyTyped(evt);
            }
        });
        getContentPane().add(rut);
        rut.setBounds(240, 50, 130, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombres:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 110, 100, 22);

        nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresActionPerformed(evt);
            }
        });
        nombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombresKeyTyped(evt);
            }
        });
        getContentPane().add(nombres);
        nombres.setBounds(240, 110, 130, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido paterno:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 160, 160, 22);

        apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellidosKeyTyped(evt);
            }
        });
        getContentPane().add(apellidos);
        apellidos.setBounds(240, 160, 130, 20);

        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 260, 110, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido materno:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 200, 160, 22);

        mat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                matKeyTyped(evt);
            }
        });
        getContentPane().add(mat);
        mat.setBounds(240, 200, 130, 20);

        jButton2.setText("Buscar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 50, 100, 23);

        jButton3.setText("Limpiar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(420, 260, 100, 23);

        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("(En caso de que el DV sea K reemplazarlo por un 0 Ej:198961710)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 80, 420, 14);

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(170, 260, 110, 23);

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(43, 260, 110, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Color-fondo-blog.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 710, 570);

        jMenu1.setText("Volver");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cerrar sesión");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        principal principal = new principal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
         inicio inicio = new inicio();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

      
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String id=rut.getText();    
    String sql="select * from funcionario where rut='"+id+"'";      
        String r;
        String a;
        String b;     
        
        if(rut.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Para buscar debe ingresar un rut");
        }
        else{
            
        
        try{
            
            ResultSet rs = con.ejecutarSQLSelect(sql);
            if (rs.next()){
                
                
                 r = rs.getString("nombre");
                 a = rs.getString("apellido_pat");
                 b = rs.getString("apellido_mat");
                
               nombres.setText(r);
               apellidos.setText(a);
               mat.setText(b);
               jButton4.setEnabled(true);
               jButton5.setEnabled(true);
               
            }else{
                JOptionPane.showMessageDialog(rootPane,"No existe el funcionario");
            }
            
            
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"No existe el funcionario");
            
        }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
               nombres.setText(null);
               apellidos.setText(null);
               mat.setText(null);
               rut.setText(null);
               jButton1.setEnabled(true);
               jButton4.setEnabled(false);
               jButton5.setEnabled(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void rutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rutKeyTyped
       if(rut.getText().length()>9){
           evt.consume();
           getToolkit().beep();
           JOptionPane.showMessageDialog(rootPane,"solo 9 digitos");
       
        }
        char c=evt.getKeyChar();
               if(c<'0' || c>'9'){
                   evt.consume();
               }  
    }//GEN-LAST:event_rutKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nam = nombres.getText();
        String ap = apellidos.getText();
        String ma = mat.getText();
        String name = nam.toUpperCase();
        String ape = ap.toUpperCase();
        String mate = ma.toUpperCase();
        String prueba = rut.getText();
        
        
        if(prueba.contains("0")){
            prueba = prueba.substring(0,prueba.length()-1);
            prueba = prueba + "k";
           
        }
        boolean respuesta;
        respuesta = validarRut(prueba);
        
        if(respuesta==false){
            JOptionPane.showMessageDialog(rootPane,"Rut invalido",
            "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else{     
        
        if (rut.getText().equals("") || name.equals("") || ape.equals("") || mate.equals("") || rut.getText().equals(null) || name.equals(null) || ape.equals(null) || mate.equals(null)){
            JOptionPane.showMessageDialog(rootPane,"No deje campos en blanco");
        } else {
        int dni= Integer.parseInt(rut.getText());
        try{
        
        
                      

         String sql = "INSERT INTO funcionario (rut,nombre,apellido_pat,apellido_mat)VALUES("+dni+",'"+name+"','"+ape+"','"+mate+"')";
        
        PreparedStatement ps=con.getConexion().prepareStatement(sql);
            
            //ps.setBinaryStream(4,fis,longitudBytes);
            
            ps.execute();
            ps.close();
        
         JOptionPane.showMessageDialog(null, "Datos Funcionario Almacenados Satisfactoriamente"); 
            //ps.execute();
            //ps.close();
          JOptionPane.showMessageDialog(rootPane,"Guardado correctamente");
        }catch(SQLException | NumberFormatException | HeadlessException x){
            JOptionPane.showMessageDialog(rootPane, "exception 2 "+x);
        }    
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String nam = nombres.getText();
        String ap = apellidos.getText();
        String ma = mat.getText();
        String name = nam.toUpperCase();
        String ape = ap.toUpperCase();
        String mate = ma.toUpperCase();
        if (rut.getText().equals("") || name.equals("") || ape.equals("") || mate.equals("") ){
            JOptionPane.showMessageDialog(rootPane,"No deje campos en blanco");
        } else {
        int dni= Integer.parseInt(rut.getText());
        try{
        

         String sql = "update funcionario set nombre='"+name+"' , apellido_pat='"+ape+"' , apellido_mat='"+mate+"' where rut="+dni;
        
        PreparedStatement ps=con.getConexion().prepareStatement(sql);
            
            //ps.setBinaryStream(4,fis,longitudBytes);
            
            ps.execute();
            ps.close();
        
         JOptionPane.showMessageDialog(null, "Datos Funcionario Actualizados Satisfactoriamente"); 
            //ps.execute();
           
            //ps.close();
          JOptionPane.showMessageDialog(rootPane,"Guardado correctamente");
        }catch(SQLException | NumberFormatException | HeadlessException x){
            JOptionPane.showMessageDialog(rootPane, "exception 2 "+x);
        }    
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        if (rut.getText().equals("") || rut.getText().equals(null) ){
            JOptionPane.showMessageDialog(rootPane,"No deje campos en blanco");
        } else {
        int dni= Integer.parseInt(rut.getText());
        try{
        

         String sql = "delete from funcionario where rut="+dni;
        
        PreparedStatement ps=con.getConexion().prepareStatement(sql);
            
            //ps.setBinaryStream(4,fis,longitudBytes);
            
            ps.execute();
            ps.close();
        
         JOptionPane.showMessageDialog(null, "Datos Funcionario Eliminados Satisfactoriamente"); 
         jButton4.setEnabled(false);
         jButton5.setEnabled(false);
            
            //ps.execute();
           
            //ps.close();
          
        }catch(SQLException | NumberFormatException | HeadlessException x){
            JOptionPane.showMessageDialog(rootPane, "exception 2 "+x);
        }    
        rut.setText(null);
        nombres.setText(null);
        apellidos.setText(null);
        mat.setText(null);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void nombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresKeyTyped
      if(nombres.getText().length()>50){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"solo 50 caracteres");
       
        }
         char c=evt.getKeyChar();
        if(((c<'a' || c>'z')&&(c<'A')|c>'Z')  &&(c!='ñ')&&( c!='Ñ')  && (c!= KeyEvent.VK_SPACE))evt.consume(); 
    }//GEN-LAST:event_nombresKeyTyped

    private void apellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidosKeyTyped
          if(apellidos.getText().length()>50){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"solo 50 caracteres");
       
        }
         char c=evt.getKeyChar();
        if(((c<'a' || c>'z')&&(c<'A')|c>'Z') &&(c!='ñ') &&( c!='Ñ')  && (c!= KeyEvent.VK_SPACE))evt.consume(); 
    }//GEN-LAST:event_apellidosKeyTyped

    private void matKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matKeyTyped
          if(mat.getText().length()>50){
           evt.consume();
           JOptionPane.showMessageDialog(rootPane,"solo 50 caracteres");
       
        }
         char c=evt.getKeyChar();
        if(((c<'a' || c>'z')&&(c<'A')|c>'Z') &&(c!='ñ' || c!='Ñ') && (c!= KeyEvent.VK_SPACE) )evt.consume(); 
    }//GEN-LAST:event_matKeyTyped

    private void nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
public static boolean validarRut(String rut) {

boolean validacion = false;
try {
rut =  rut.toUpperCase();
rut = rut.replace(".", "");
rut = rut.replace("-", "");
int rutAux = Integer.parseInt(rut.substring(0, rut.length() - 1));

char dv = rut.charAt(rut.length() - 1);

int m = 0, s = 1;
for (; rutAux != 0; rutAux /= 10) {
s = (s + rutAux % 10 * (9 - m++ % 6)) % 11;
}
if (dv == (char) (s != 0 ? s + 47 : 75)) {
validacion = true;
}

} catch (java.lang.NumberFormatException e) {
} catch (Exception e) {
}
return validacion;
}
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField mat;
    private javax.swing.JTextField nombres;
    private javax.swing.JTextField rut;
    // End of variables declaration//GEN-END:variables
}
