/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portafolio;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        this.setTitle("Inicio Sesión");
        
        this.setResizable(false);
        //Línea 1
        this.setSize(new Dimension(500, 500));
        
        //Línea 2
        this.setMinimumSize(new Dimension(500, 250));
        this.setLocationRelativeTo(inicio.this);
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagen/descarga.jpg"));
        this.setIconImage(ico);
        transparencia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        botoninicio = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        b1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre de usuario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 110, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 180, 100, 30);
        getContentPane().add(username);
        username.setBounds(270, 120, 120, 20);

        botoninicio.setText("Iniciar Sesión");
        botoninicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botoninicioMouseClicked(evt);
            }
        });
        botoninicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoninicioActionPerformed(evt);
            }
        });
        getContentPane().add(botoninicio);
        botoninicio.setBounds(170, 250, 130, 23);

        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordKeyPressed(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(270, 190, 120, 20);

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/admin1.png"))); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(330, 250, 120, 100);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Administrador de Usuario");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 340, 180, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Color-fondo-blog.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -40, 720, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoninicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botoninicioMouseClicked
       String usuario="admin";
       String contraseña="admin1234";
       String  Pass = new String (Password.getPassword());
       if (username.getText().equals(usuario) && Pass.equals(contraseña)){
            principal principal = new principal();
            principal.setVisible(true);
            dispose();
       }else{
            JOptionPane.showMessageDialog(rootPane,"ERROR Usuario o Contraseña Incorrecta.",
                                     "ERROR", JOptionPane.ERROR_MESSAGE);
       }
        
       
       
    }//GEN-LAST:event_botoninicioMouseClicked

    public void transparencia(){
    b1.setOpaque(false);
    b1.setContentAreaFilled(false);
    b1.setBorderPainted(false);
    
  
    
}
    private void botoninicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoninicioActionPerformed
      
    }//GEN-LAST:event_botoninicioActionPerformed

    private void PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){ 
        botoninicioMouseClicked(null);
} 
    }//GEN-LAST:event_PasswordKeyPressed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
    
        inicio_usu inicio_usu = new inicio_usu();
            inicio_usu.setVisible(true);
            
    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton b1;
    private javax.swing.JButton botoninicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
