/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portafolio;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class insumos extends javax.swing.JFrame {
      FileInputStream fis;
          int longitudBytes;
          conexion con = Portafolio.conexion;
    /**
     * Creates new form insumos
     */
    public insumos() {
        initComponents();
        this.setTitle("Insumos");
         
        
        this.setResizable(false);
        //Línea 1
        this.setSize(new Dimension(700, 500));
        
        //Línea 2
        this.setMinimumSize(new Dimension(500, 250));
        this.setLocationRelativeTo(insumos.this);
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagen/descarga.jpg"));
        this.setIconImage(ico);
        mostrarcat();
        mostrare();
        jButton3.setEnabled(false);
        jButton2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoria = new javax.swing.JComboBox<>();
        nombre_insumo = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        estado = new javax.swing.JComboBox<>();
        lblfoto = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lb_nom = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(categoria);
        categoria.setBounds(150, 110, 130, 20);
        getContentPane().add(nombre_insumo);
        nombre_insumo.setBounds(150, 70, 130, 20);

        stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stockKeyTyped(evt);
            }
        });
        getContentPane().add(stock);
        stock.setBounds(150, 160, 130, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Estado:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 210, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Categoria:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 110, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 70, 80, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 160, 80, 20);

        jButton1.setText("ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 300, 100, 23);

        jButton2.setText("modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 300, 110, 23);

        jButton3.setText("eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 300, 100, 23);

        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(estado);
        estado.setBounds(150, 210, 130, 20);

        lblfoto.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lblfoto);
        lblfoto.setBounds(390, 10, 140, 170);

        jButton4.setText("imagen");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(410, 200, 110, 23);

        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(290, 70, 80, 23);

        jButton6.setText("Limpiar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(450, 300, 90, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Color-fondo-blog.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-30, -10, 750, 470);
        getContentPane().add(lb_nom);
        lb_nom.setBounds(200, 20, 70, 20);

        jMenu1.setText("Volver");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cerrar sesión");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        principal principal = new principal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        inicio inicio = new inicio();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked


     public void mostrare(){
         String sql="select descripcion from estado";  
  
       
          try{
            
            ResultSet rs = con.ejecutarSQLSelect(sql);
            estado.removeAllItems();
            
            
            while (rs.next()){
                estado.addItem(rs.getString(1));
          
            }
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"No existe ");
            
        }
        }
     
     
  
     public void mostrarcat(){
         String sql="select descripcion from categoria";  
  
         
          try{
            
            ResultSet rs = con.ejecutarSQLSelect(sql);
           
            categoria.removeAllItems();
          
            while (rs.next()){
                
                categoria.addItem(rs.getString(1));
       
            }
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"No existe ");
            
        }
        }
     
     public String devuelveid(String nombre){
          String sql="select id_categoria from categoria where descripcion='"+nombre+"'";  
  
         
          try{
            
            ResultSet rs = con.ejecutarSQLSelect(sql);
           
            
          
            while (rs.next()){
                
                nombre = rs.getString(1);
       
            }
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"No existe ");
            
        }
         return nombre;
     }
     
     public String devuelveestado (String nombre){
          String sql="select id_estado from estado where descripcion='"+nombre+"'";  
  
         
          try{
            
            ResultSet rs = con.ejecutarSQLSelect(sql);
           
            
          
            while (rs.next()){
                
                nombre = rs.getString(1);
       
            }
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"No existe ");
            
        }
         return nombre;
     }
     
     
    
         
         

    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if (nombre_insumo.getText().equals("") || nombre_insumo.getText().equals(null) ){
            JOptionPane.showMessageDialog(rootPane,"No deje campos en blanco");
        } else {
        
        try{
        

         String sql = "delete from insumo where nombre='"+nombre_insumo.getText()+"'";
        
        PreparedStatement ps=con.getConexion().prepareStatement(sql);
            
            //ps.setBinaryStream(4,fis,longitudBytes);
            
            ps.execute();
            ps.close();
        
         JOptionPane.showMessageDialog(null, "Datos Insumos Eliminados Satisfactoriamente"); 
         jButton2.setEnabled(false);
         jButton3.setEnabled(false);
         jButton1.setEnabled(true);
            //ps.execute();
           
            //ps.close();
          
        }catch(SQLException | NumberFormatException | HeadlessException x){
            JOptionPane.showMessageDialog(rootPane, "exception 2 "+x);
        }    
        nombre_insumo.setText(null);
        
        stock.setText(null);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      
        lblfoto.setIcon(null);
        JFileChooser j=new JFileChooser();
        j.setFileSelectionMode(JFileChooser.FILES_ONLY);//solo archivos y no carpetas
        int estado=j.showOpenDialog(null);
        if(estado== JFileChooser.APPROVE_OPTION){
            try{
                fis=new FileInputStream(j.getSelectedFile());
                //necesitamos saber la cantidad de bytes
                this.longitudBytes=(int)j.getSelectedFile().length();
                try {
                    Image icono=ImageIO.read(j.getSelectedFile()).getScaledInstance
                            (lblfoto.getWidth(),lblfoto.getHeight(),Image.SCALE_DEFAULT);
                    lblfoto.setIcon(new ImageIcon(icono));
                    lblfoto.updateUI();

                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane, "imagen: "+ex);
                }
            }catch(FileNotFoundException ex){
                ex.printStackTrace();
            }
        }  
    }//GEN-LAST:event_jButton4ActionPerformed
public boolean devuelvenombre(String nombre,boolean respuesta){
    
          String sql="select nombre from insumo where nombre='"+nombre+"'";  
  
         
          try{
            
            ResultSet rs = con.ejecutarSQLSelect(sql);
           
            
          
            while (rs.next()){
                
                nombre = rs.getString(1);
                respuesta = true;
       
            }
        
        }catch(Exception ex){
            respuesta = false;
          
        }
        
         return respuesta;
     }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
      
        String nom_insumo=nombre_insumo.getText();
        String stoc=stock.getText();
       
        String obtengo = (String) categoria.getSelectedItem();
        String resultado = devuelveid(obtengo);
        int fincat= Integer.parseInt(resultado);
        
        String obtengoestado = (String) estado.getSelectedItem();
        String resultadoestado = devuelveestado(obtengoestado);
        int finest= Integer.parseInt(resultadoestado);
        boolean k = false;
       boolean comnombre = devuelvenombre(nom_insumo,k);
     
        System.out.print(comnombre+nom_insumo);
     if(nombre_insumo.getText().equals("") || stock.getText().equals("")){
         JOptionPane.showMessageDialog(null, "Campos en blanco"); 
     } else if(comnombre == true){
         
             JOptionPane.showMessageDialog(null, "Ya existe insumo con dicho nombre"); 
             }
     
     else{
         
     
        try{           

         String sql = "INSERT INTO \"insumo\"(id_categoria, nombre, stock, imagen,estado) VALUES (?, ?, ?,?,?)";
        
       
        PreparedStatement ps=con.getConexion().prepareStatement(sql);
            ps.setInt(1,(fincat));
            ps.setString(2,nom_insumo);
            ps.setInt(3,Integer.parseInt(stoc));
            ps.setBinaryStream(4,fis,longitudBytes);
            ps.setInt(5,(finest));
            
            ps.execute();
            ps.close();
        
         JOptionPane.showMessageDialog(null, "Datos Insumo Almacenados Satisfactoriamente"); 
            
        }catch(SQLException | NumberFormatException | HeadlessException x){
            JOptionPane.showMessageDialog(rootPane, "exception 2 "+x);
        }    
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
          
           String sql="select categoria.descripcion, estado.descripcion ,stock,imagen,nombre from insumo, categoria,estado where nombre='"+nombre_insumo.getText()+"' and insumo.id_categoria=categoria.id_categoria and estado=id_estado";
        String categ;
        String nom;
        String stoc;
        String est;
        String lbl_nom;
       
        ImageIcon foto;
        InputStream is;
        
        if(nombre_insumo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar nombre para buscar ");
        }else{
            
        
            try{
            
            ResultSet rs = con.ejecutarSQLSelect(sql);
           
            if (rs.next()){
                
                categ =  rs.getString(1);
               
                stoc = rs.getString(3);
                is = rs.getBinaryStream(4);
                est = rs.getString(2);
                lbl_nom=rs.getString(5);
                
             BufferedImage bi = ImageIO.read(is);
                foto = new ImageIcon(bi);
                
                Image img = foto.getImage();
                Image newimg = img.getScaledInstance(140, 170, java.awt.Image.SCALE_SMOOTH);
                
                ImageIcon newicon = new ImageIcon(newimg);
                
                lblfoto.setIcon(newicon);
                
               categoria.setSelectedItem(categ);
               estado.setSelectedItem(est);
               stock.setText(stoc);
               lb_nom.setText(lbl_nom);
               

                jButton2.setEnabled(true);
                 jButton3.setEnabled(true);
                 jButton1.setEnabled(false);
              
               
            }else{
                JOptionPane.showMessageDialog(rootPane,"No existe insumo");
            }
            
            
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"exception: "+ex);
        }
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void stockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockKeyTyped
        if(stock.getText().length()>9){
           evt.consume();
           getToolkit().beep();
           JOptionPane.showMessageDialog(rootPane,"Maximo solo 3 digitos");
       
        }
        char c=evt.getKeyChar();
               if(c<'0' || c>'9'){
                   evt.consume();
               } 
    }//GEN-LAST:event_stockKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nom_insumo=nombre_insumo.getText();
        String stoc=stock.getText();
        String lbl_nom=lb_nom.getText();
       
        String obtengo = (String) categoria.getSelectedItem();
        String resultado = devuelveid(obtengo);
        int fincat= Integer.parseInt(resultado);
        
        String obtengoestado = (String) estado.getSelectedItem();
        String resultadoestado = devuelveestado(obtengoestado);
        int finest= Integer.parseInt(resultadoestado);
        
 
     if(nombre_insumo.getText().equals("") || stock.getText().equals("")){
         JOptionPane.showMessageDialog(null, "Campos en blanco"); 
     }   else{
         
        try{
        
         String sql = "update insumo set nombre='"+nom_insumo+"' , id_categoria="+fincat+" , stock="+stoc+" , estado="+finest+" , imagen=? where nombre='"+lbl_nom+"'";

       
        PreparedStatement ps=con.getConexion().prepareStatement(sql);
          ps.setBinaryStream(1,fis,longitudBytes);
            
            ps.execute();
            ps.close();
        
         JOptionPane.showMessageDialog(null, "Datos Insumo Almacenados Satisfactoriamente"); 
            
        }catch(SQLException | NumberFormatException | HeadlessException x){
            JOptionPane.showMessageDialog(rootPane, "exception 2 "+x);
        }    
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        nombre_insumo.setText(null);
        stock.setText(null);
        lblfoto.setIcon(null);
        jButton1.setEnabled(true);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insumos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insumos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lb_nom;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JTextField nombre_insumo;
    private javax.swing.JTextField stock;
    // End of variables declaration//GEN-END:variables
}
