/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package portafolio;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felipe
 */
public class reportes extends javax.swing.JFrame {

    conexion con = Portafolio.conexion;
    DefaultTableModel model= new DefaultTableModel();
    
    public reportes() {
        initComponents();
        this.setTitle("Principal");
        
        this.setResizable(false);
        //Línea 1
        this.setSize(new Dimension(700, 500));
        
        //Línea 2
        this.setMinimumSize(new Dimension(500, 250));
        this.setLocationRelativeTo(reportes.this);
        Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagen/descarga.jpg"));
        this.setIconImage(ico);
        this.jTable1.setModel(model);
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        report = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cargar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione reporte:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 100, 150, 22);

        report.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(report);
        report.setBounds(300, 100, 100, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 180, 480, 160);

        cargar.setText("Cargar");
        cargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarMouseClicked(evt);
            }
        });
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });
        getContentPane().add(cargar);
        cargar.setBounds(430, 100, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Color-fondo-blog.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -16, 940, 590);

        jMenu2.setText("Volver");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void eliminar(){
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int a = jTable1.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        tb.removeRow(tb.getRowCount()-1);
        } 
        //cargaTicket();
    }


    private void cargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarMouseClicked
        
       String eleccion = (String) report.getSelectedItem();
        
        switch(eleccion){
        
        case "Estado":
            eliminar();
          model.setColumnCount(0);

            
             model.addColumn("Descripcion");
             
    String sql="select * from vistaestado"; 
      String [] arreglo = new String[6];

        
        try{
            ResultSet rs = con.ejecutarSQLSelect(sql);
            while (rs.next()){
                
               
                
            arreglo[0] = rs.getString(1);
            
           
          
           
        model.addRow(arreglo);
             
            }
            
            
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"No existe Categoria ingresada"+ex);
            
        }
        break;
        case "Funcionarios":
            eliminar();
            model.setColumnCount(0);
                  model.addColumn("Rut");
                  model.addColumn("Nombre");
                  model.addColumn("Apellido paterno");
                  model.addColumn("Apellido materno");
    String sq="select * from vistafuncionario"; 
      String [] arregl = new String[6];

        
        try{
            ResultSet rs = con.ejecutarSQLSelect(sq);
            while (rs.next()){
                
               
                
            arregl[0] = rs.getString(1);
            arregl[1] = rs.getString(2);
            arregl[2] = rs.getString(3);
            arregl[3] = rs.getString(4);
           
          
           
        model.addRow(arregl);
             
            }
            
            
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"No existe Categoria ingresada"+ex);
            
        }
            break;
            
            case "Categorias":
            eliminar();
            model.setColumnCount(0);
                  model.addColumn("Descripcion");
                  
    String s="select * from vistacategoria"; 
      String [] arreg = new String[6];

        
        try{
            ResultSet rs = con.ejecutarSQLSelect(s);
            while (rs.next()){
                
               
                
            arreg[0] = rs.getString(1);
            
           
          
           
        model.addRow(arreg);
             
            }
            
            
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"No existe Categoria ingresada"+ex);
            
        }
            break;
               case "Insumos":
            eliminar();
            model.setColumnCount(0);
                  model.addColumn("Nombre");  
                  model.addColumn("Categoria");
                  model.addColumn("Estado");
                  model.addColumn("Stock");
                  model.addColumn("Imagen");
                  
                  
    String w="select * from vistainsumo"; 
      Object [] arre = new Object[6];
     jTable1.setDefaultRenderer(Object.class, new tablaimagen());
         ImageIcon foto;
        InputStream is;
        try{
            ResultSet rs = con.ejecutarSQLSelect(w);
            while (rs.next()){
                
               
                
            arre[0] = rs.getObject(5);
            arre[1] =  rs.getObject(1);
            arre[2] = rs.getObject(2);
            arre[3] = rs.getObject(3);
            
            
             is = rs.getBinaryStream(4);
                
          BufferedImage bi = ImageIO.read(is);
                foto = new ImageIcon(bi);
                
                Image img = foto.getImage();
                Image newimg = img.getScaledInstance(140, 170, java.awt.Image.SCALE_SMOOTH);
                
                ImageIcon newicon = new ImageIcon(newimg);
           arre[4] = new JLabel(newicon);
        model.addRow(arre);
       
             
            }
            
            
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane,"Error"+ex);
            
        }
            break;
    }
     

    }//GEN-LAST:event_cargarMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
      principal principal = new principal();
      principal.setVisible(true);
      dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargarActionPerformed

    public void mostrar(){
                report.removeAllItems();
		report.addItem("Funcionarios");
		report.addItem("Insumos");
		report.addItem("Categorias");
                report.addItem("Estado");
        }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> report;
    // End of variables declaration//GEN-END:variables
}
